### ISSUE TITLE
A stupid question, how secure is it?

### ISSUE THREAD

**Issue by sunjoomoon** [defrex/django-encrypted-fields#19]
Say, if social security number is encrypted, in general, how tough is it to crack it down?

**Comment by defrex** [comment]
That very much depends how it's encrypted. Keyczar can use a lot of different methods. That said, most of them are going to be extremely strong; infeasible to crack given the technology we know about.

However, if someone gets their hands on your keys, it's a different story. If you're worried about security, focus of securing your keys as much as possible.

**Comment by sunjoomoon** [comment]
Well noted and indeed makes sense.
