### ISSUE TITLE
location of fieldkeys

### ISSUE THREAD

**Issue by Awmusic12635** [defrex/django-encrypted-fields#20]
`ENCRYPTED_FIELDS_KEYDIR = '/path/to/fieldkeys'`

Is this relative to my project folder?

so / would be considered the top of my project folder.

**Comment by defrex** [comment]
It is not relative to your project folder. However, you can make it so thusly.

```python
import os

PROJECT_DIR =os.path.dirname(os.path.dirname(__file__)) # assuming $PROJECT_DIR/somename/settings.py

ENCRYPTED_FIELDS_KEYDIR = os.path.join(PROJECT_DIR, 'mycoolpath/keys')

```
