### ISSUE TITLE
char field max length

### ISSUE THREAD

**Issue by Awmusic12635** [defrex/django-encrypted-fields#21]
Trying to make a migration and having an issue:

```
SystemCheckError: System check identified some issues:

ERRORS:
app.Server.password: (fields.E120) CharFields must define a 'max_length' attribute.
```

I saw there was a variable for "enforce_max_length", however that doesn't appear to get rid of the error. It still appears to complain if that is there. What is the proper way to handle this, enforce_max_length + max_length or just max_length?

**Comment by defrex** [comment]
Can you show me your field definition?

**Comment by Awmusic12635** [comment]
password=EncryptedCharField()

or

password=EncryptedCharField(enforce_max_length=60)

has this error.

if I do password=EncryptedCharField(enforce_max_length=60,max_length=60) it goes away, but I don't know if that hurts any of the way it operates.

**Comment by defrex** [comment]
Like a normal `CharField`, you need to specify `max_length`. `enforce_max_length` should be `True` or `False`, rather then a length value. It determines if a `ValueError` is raised when you try to save a longer value.
